version: '3'
networks:
  tpfinal-test:
    external: true
services:
  mysql-tpfinal:
    image: mysql
    container_name: mysql-tpfinal
    networks:
      - tpfinal-test
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: node-complete
    ports:
      - "50:3306"

  phpmyadmin-tpfinal:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-tpfinal
    networks:
      - tpfinal-test
    environment:
      PMA_HOST: mysql-tpfinal
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "52:80"
    depends_on:
      - mysql-tpfinal

  mi-app-tpfinal:
    build:
      context: ./Skyloft
    image: josuevirreyra/hia-tpfinal-test:latest
    container_name: mi-app-tpfinal
    networks:
      - tpfinal-test
    links:
      - mysql-tpfinal
    ports:
      - "51:3000"
    restart: unless-stopped

  watchtower:
    container_name: watchtower-tpfinal
    networks:
      - tpfinal-test
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_CLEANUP=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - mi-app-tpfinal
