name: Test CI/CD

on:
  push:
    branches:
      - master

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: SetUp Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and Push App
        uses: docker/build-push-action@v5
        with:
          context: ./Skyloft
          file: ./Skyloft/Dockerfile.dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/hia-tpfinal-test:latest
